[font]
size = 11.0

[font.bold]
family = "RobotoMono Nerd Font Mono"
style = "Bold"

[font.bold_italic]
family = "RobotoMono Nerd Font Mono"
style = "Bold Italic"

[font.italic]
family = "RobotoMono Nerd Font Mono"
style = "Italic"

[font.normal]
family = "RobotoMono Nerd Font Mono"
style = "Regular"

[shell]
program = "/bin/zsh"
args = ["-l"]

[env]
TERM = "xterm-256color"

[window]

opacity = 0.9

padding.x = 10
padding.y = 10

# Colors (Alabaster Dark)
# author tonsky

[colors.primary]
background = '#0E1415'
foreground = '#CECECE'

[colors.cursor]
text = '#0E1415'
cursor = '#CECECE'

[colors.normal]
black = '#0E1415'
red = '#e25d56'
green = '#73ca50'
yellow = '#e9bf57'
blue = '#4a88e4'
magenta = '#915caf'
cyan = '#23acdd'
white = '#f0f0f0'

[colors.bright]
black = '#777777'
red = '#f36868'
green = '#88db3f'
yellow = '#f0bf7a'
blue = '#6f8fdb'
magenta = '#e987e9'
cyan = '#4ac9e2'
white = '#FFFFFF'
