# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
# we will manage the disk ourself
{ config, lib, pkgs, modulesPath, ... }:

{
  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";


  virtualisation.vmVariant = {
      virtualisation = {
        memorySize = 4096;   # MiB
        cores = 4;
        diskSize = 16384;    # MiB, the qcow2 size
        # graphics = false;    # serial console instead of a QEMU window

        # host:guest port forwarding
        # forwardPorts = [
        #   { from = "host"; host.port = 2222; guest.port = 22; }
        #   { from = "host"; host.port = 8080; guest.port = 80; }
        # ];

        # sharedDirectories.stuff = {
        #   source = "/home/me/shared";
        #   target = "/mnt/shared";
        # };

        # anything else straight to qemu
        qemu.options = [
         "-cpu host"

         "-vga virtio"
         "-display gtk,grab-on-hover=on"
        ];
      };
    };
}
