# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
# we will manage the disk ourself
{ self, config, lib, pkgs, modulesPath, ... }:
let
  vmConfig = {
      virtualisation = {
        memorySize = 4096;   # MiB
        cores = 8;
        diskSize = 16384;    # MiB, the qcow2 size
        # graphics = false;    # serial console instead of a QEMU window

        # host:guest port forwarding
        # forwardPorts = [
        #   { from = "host"; host.port = 2222; guest.port = 22; }
        #   { from = "host"; host.port = 8080; guest.port = 80; }
        # ];

        # this help testing impermanence
        # sharedDirectories.persist = {
        #   # these won't work in pure mode
        #   # source = builtins.toString ~/.build/vm_persist;
        #   # source = builtins.toString ../../../.build/vm_persist;
        #   # source = "${self}/.build";
        #   # use absolute path instead, clean these up latter
        #   source = "/var/tmp/nixos-vmtest-persist";
        #   target = "/nix/persist";
        # };
        #

        # anything else straight to qemu
        qemu.options = [
         "-cpu host"

         "-vga virtio"
         "-display gtk,grab-on-hover=on"
        ];
      };
    };
in
{
  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";


  virtualisation.vmVariant = lib.mkMerge [vmConfig];
  virtualisation.vmVariantWithDisko = lib.mkMerge [vmConfig {

    # disko need this to build the impermanence setup
    virtualisation.fileSystems."/home/arch".neededForBoot = true;
    virtualisation.fileSystems."/nix".neededForBoot = true;
    virtualisation.fileSystems."/".neededForBoot = true;
    #
    virtualisation.sharedDirectories.persist = {
      # these won't work in pure mode
      # source = builtins.toString ~/.build/vm_persist;
      # source = builtins.toString ../../../.build/vm_persist;
      # source = "${self}/.build";
      # use absolute path instead, clean these up latter
      source = "/var/tmp/nixos-vmtest-persist";
      target = "/nix/persist";
    };

  }];
  virtualisation.vmVariantWithBootLoader = lib.mkMerge [vmConfig];

}
